name:                cy
version:             0.1.0.0
github:              "githubuser/cy"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cfoust/cy#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- parsec
- posix-pty
- process
- signal
- terminal-size
- text
- time
- unix
- utf8-string

library:
  source-dirs: src

executables:
  cy-exe:
    main:                Main.hs
    source-dirs:         app/record
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cy

  cy-borg:
    main:                Main.hs
    source-dirs:         app/borg
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cy

tests:
  cy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cy
