[book]
language = "en"
multilingual = false
src = "src"
title = "cy documentation"
description = "A next-generation terminal multiplexer that records everything you do."
authors = ["Caleb Foust"]

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
site-url = "/cy/"
git-repository-url = "https://github.com/cfoust/cy"

[preprocessor.storybook]
command = "python3 storybook.py"
after = [ "links" ]

[preprocessor.gendoc]
command = "python3 gendoc.py"
before = [ "storybook" ]
