[book]
language = "en"
multilingual = false
src = "src"
title = "cy documentation"
description = "A next-generation terminal multiplexer that records everything you do."
authors = ["Caleb Foust"]

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
site-url = "/cy/"

[preprocessor.storybook]
command = "python3 storybook.py"
after = [ "links" ]
