name: Deploy documentation
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push a branch
      pages: write # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - uses: charmbracelet/vhs-action@v2

      - id: cy
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: cfoust/cy

      - name: Build
        run: >
          go build
          -ldflags "-X github.com/cfoust/cy/pkg/version.Version=${{ steps.cy.outputs.release }}"
          -o docs/stories
          ./cmd/stories/main.go

      - name: Install the latest VHS
        run: |
          git clone https://github.com/charmbracelet/vhs.git
          cd vhs
          go build -o ../vhs-bin .
          cd ..
          rm -r vhs
          mv vhs-bin docs/vhs

      - name: Build book
        run: |
          go run cmd/docs/main.go api > docs/src/generated-api.md
          go run cmd/docs/main.go frames > docs/src/generated-frames.md
          go run cmd/docs/main.go animations > docs/src/generated-animations.md
          cd docs
          mdbook build

      - name: Setup pages
        uses: actions/configure-pages@v2
      - name: Upload site
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "docs/book"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
